### ISSUE TITLE
Masters that depend on non-masters force the latter to load as masters

### ISSUE THREAD

**Issue by Ortham** [Ortham/libloadorder#39]
It's possible to create a master that depends on a non-master, and the game will load it, but in doing so the non-master will be moved so that it loads before the master (unverified). Libloadorder doesn't currently handle this case, as it doesn't check plugin masters at all.

I'm hoping this behaviour gets classified as a bug and fixed by Bethesda, since (IIRC) the analogous behaviour with a master depending on a non-master is a crash on load, but filing this issue to ensure I don't forget about it.

*Edit: Removed mentions of light masters, it's actually about ESMs, which all light masters were when this issue was originally filed.*

**Comment by Freso** [comment]
> It's possible to create a light master that depends on a non-master

It's possible to make any ESM file have a non-ESM file as a `MAST`er, not limited to ESL-flagged plugins. (I'm guessing this issue was filed while ESLs were still getting figured out.)

Almost a year later now and the behaviour hasn't been "fixed", so I'd assume it's here to stay.

**Comment by WrinklyNinja** [comment]
> It's possible to make any ESM file have a non-ESM file as a MASTer, not limited to ESL-flagged plugins. (I'm guessing this issue was filed while ESLs were still getting figured out.)

Do ESMs that depend on non-ESMs cause the non-ESM to load before the ESM too?

**Comment by WrinklyNinja** [comment]
OK, from my testing in Skyrim SE, if an ESM depends on a non-ESM, the non-ESM is loaded immediately before it, as if it were an ESM. I need to test this with Skyrim and Oblivion...

**Comment by WrinklyNinja** [comment]
I've seen the same behaviour in Oblivion. Still downloading Skyrim, but I don't expect it'll be different.

I'll also note that the "plugin hoisting" only happens across the ESM/non-ESM boundary: if A.esp has B.esp as a master and A.esp loads before B.esp in plugins.txt (or equivalent game mechanism), they load in that order in-game, so that any records in B.esp that are overwritten by A.esp have their overwrites ignored.

**Comment by WrinklyNinja** [comment]
Fixed in 89f2ddc66909d6bbcbd9b4e7b5ea1775981a1c79.

**Comment by WrinklyNinja** [comment]
Reopening this as though reading a load order that includes plugins that are hoisted at runtime is now correct, setting such a load order is not supported, so I'm going to revert the merge into `master` until that's fixed.

**Comment by WrinklyNinja** [comment]
I checked the behaviours of Wrye Bash and xEdit when an ESM depends on a non-ESM:

- Wrye Bash displays the load order as if the ESM did not depend on the non-ESM, so the non-ESM is in its usual position. It's impossible to move the non-ESM before the ESM that depends on it, so the ESM has an orange "loads before its masters" checkbox.
- xEdit fails to load plugins: `[00:02] Background Loader: Fatal: <Exception: "Quest Award Leveller - Knights of the Nine.esp" requires master "Knights.esp" to be loaded before it.>` (I set the master flag for `Quest Award Leveller - Knights of the Nine.esp`.)

This behaviour isn't something that I'd come across in the 10 years experience before I filed this issue, so the above isn't surprising. That ESMs load before non-ESMs is pretty widely assumed, e.g. I think LOOT will fail to sort a load order with an ESM that depends on a non-ESM due to a perceived cycle, and that's also why libloadorder will fail to set such a load order.

I think that in the interests of correctness and accuracy, libloadorder should accept load orders that have a non-ESM loading before ESMs, if the next ESM has it as a master. It should probably also error if:

- an ESM has a non-ESM as a master
- the non-ESM is present in the load order
- the non-ESM does not load between the ESM that has it as a master and the previous ESM if there is one (the ESM could have multiple non-ESMs as masters).

That way libloadorder helps ensure that the load order reflects the order that records are loaded in.

**Comment by WrinklyNinja** [comment]
`set_active_plugins()` and `activate()` are proving tricky to fix because they add plugins to the load order when activating them, if they're not already in the load order. However, given the existing load order:

```
master.esm
non_master_plugin_1.esp
non_master_plugin_2.esp
```

If activating `depends_on_non_master_plugin_2.esm`, it can't go immediately after `master.esm`, because it needs to load after `non_master_plugin_2.esp`, but it can't load after `non_master_plugin_1.esp`.

The solution is to move `non_master_plugin_2.esp` before `non_master_plugin_2.esp`, then insert and activate `depends_on_non_master_plugin_2.esm`, but in general I think that moving other plugins around when activating a plugin is unexpected and undesirable. An alternative would be to just error out if the plugin being activated can't be added to the load order without moving another plugin, or to go a step further and error out if the plugin being activated doesn't already have a load order position (which is probably the least surprising option).

I'm currently leaning towards the final option, as it's the simplest in terms of behaviour and implementation, and though it needs an extra function call from clients, it's more explicit and gives them more control.

**Comment by Ortham** [comment]
Done as of 12fa4c39e227aea01da64419ce6d5d759567c20f.
